.TH ABSTRACT 1 "30 September 2001" "" ""
.SH NAME
abstract \- Abstarct Irrelevant Environment Information 
.SH SYNOPSIS
.nf
.BI atacs " -oa"
.br
.BI atacs> " abstract"
.fi
.SH DESCRIPTION
.B abstract
marks irrelevant environment information so that it can be removed allowing
for more efficient timing analysis for synthesis and verification. 
.SH OPTIONS
.TP
.BI \-oa
Enables abstraction from the command line.
.TP
.BI abstract
Enables abstraction in the interactive shell.
.SH CREDITS
.B abstract
was primarily written by Hao Zheng (hao@vlsigroup.elen.utah.edu).
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR pored (1)
.BR http://www.async.ece.utah.edu
