.TH BDD 1 "15 Novermber 2000" "" ""
.SH NAME
bdd \- Synthesis Using the BDD Algorithm
.SH SYNOPSIS
.nf
.BI atacs " -yb"
.br
.BI atacs> " bdd"
.fi
.SH DESCRIPTION
.B bdd
uses the bdd algorithm for synthesis.  This algorithm uses BDD to represent
all possible covers.
.SH OPTIONS
.TP
.BI \-yb
Uses bdd algorithm from the command line.
.TP
.BI bdd
Uses bdd algorithm in the interactive shell.
.SH CREDITS
.B bdd
was primarily written by Robert Thacker (thacker@vlsigroup.ece.utah.edu).
.SH "SEE ALSO"
.BR single (1)
.BR multicube (1)
.BR direct (1)
.BR http://www.async.elen.utah.edu
