.TH DOT 1 "30 September 2001" "" ""
.SH NAME
dot \- Use DOT for Displaying Graphs 
.SH SYNOPSIS
.nf
.BI atacs " -od"
.br
.BI atacs> " dot"
.fi
.SH DESCRIPTION
.B dot
selects whether Bell Lab's DOT program for displaying graphs rather than
Rokicki's PARG.
.SH OPTIONS
.TP
.BI \-od
Enables the use of DOT from the command line.
.TP
.BI dot
Enables the use of DOT in the interactive shell.
.SH CREDITS
.B dot
was primarily written by Jeff Cuthbert.
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR shower (1)
.BR showrsg (1)
.BR showstat (1)
.BR shownet (1)
.BR printer (1)
.BR printrsg (1)
.BR printstat (1)
.BR printreg (1)
.BR printnet (1)
.BR http://www.async.ece.utah.edu
