.TH GATELEVEL 1 "30 September 2001" "" ""
.SH NAME
gatelevel \- Standard-C Implementation Technology
.SH SYNOPSIS
.nf
.BI atacs " -os"
.br
.BI atacs> " gatelevel"
.fi
.SH DESCRIPTION
.B gatelevel
turns gate-level implementation mode ON and OFF.  When gate-level 
implementation mode is on, the covers found must satisfy the entrance 
constraint which results in gate-level hazard-free circuit implementations.
.SH OPTIONS
.TP
.BI \-ol
Enables standard-C technology from the command line.
.TP
.BI gatelevel
Enables standard-C technology in the interactive shell.
.SH CREDITS
.B gatelevel
was primarily written by Chris Myers (myers@vlsigroup.elen.utah.edu).
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR atomic (1)
.BR gc (1)
.BR burstgc (1)
.BR burst2l (1)
.BR http://www.async.ece.utah.edu
