.TH GC 1 "30 September 2001" "" ""
.SH NAME
gc \- Generalized-C Implementation Technology
.SH SYNOPSIS
.nf
.BI atacs " -og"
.br
.BI atacs> " gc"
.fi
.SH DESCRIPTION
.B gc
selects generalized C-elements as the target technology.
With this selection, only a covering constraint needs to be satisfied
during synthesis and the covers for each excitation region are allowed
to intersect.  
.SH OPTIONS
.TP
.BI \-og
Enables generalized-C technology from the command line.
.TP
.BI gc
Enables generalized-C technology in the interactive shell.
.SH CREDITS
.B gc
was primarily written by Chris Myers (myers@vlsigroup.elen.utah.edu).
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR atomic (1)
.BR gatelevel (1)
.BR burstgc (1)
.BR burst2l (1)
.BR http://www.async.ece.utah.edu
