.TH GEOMETRIC 1 "15 Novermber 2000" "" ""
.SH NAME
geometric \- Geometric Timing Analysis
.SH SYNOPSIS
.nf
.BI atacs " -tg"
.br
.BI atacs> " geometric"
.fi
.SH DESCRIPTION
.B geometric
is a timing analysis method that uses zones represented by difference
bound matrices to explore a reachable state space.  
.SH OPTIONS
.TP
.BI \-tg
Enables the geometric method from the command line.
.TP
.BI geometric
Enables the geometric method in the interactive shell.
.SH CREDITS
.B geometric
was primarily written by Wendy Belluomini
(wendy@vlsigroup.elen.utah.edu).
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR untimed (1)
.BR posets (1)
.BR bag (1)
.BR bap (1)
.BR baptdc (1)
.BR http://www.async.ece.utah.edu
