.TH LHPNBDD 1 "13 December 2006" "" ""
.SH NAME
lhpnbdd \- Binary Decision Diagram Based LHPN Analysis
.SH SYNOPSIS
.nf
.BI atacs " -tB"
.br
.BI atacs> " lhpnbdd"
.fi
.SH DESCRIPTION
.B lhpnbdd
is an LHPN analysis method that represents the state space using BDD by mapping inequalities to BDD variables.  
.SH OPTIONS
.TP
.BI \-tB
Enables the lhpnbdd method from the command line.
.TP
.BI lhpnbdd
Enables the lhpnbdd method in the interactive shell.
.SH CREDITS
.B lhpnbdd
was primarily written by David Walter (dwalter@vlsigroup.ece.utah.edu).
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR loadlhpn (1)
.BR storelhpn (1)
.BR showlhpn (1)
.BR loadvhdl (1)
.BR lhpndbm (1)
.BR http://www.async.ece.utah.edu
