.TH LHPN 1 "14 December 2006" "" ""
.SH NAME
lhpndbm \- DBM based analyzer for LHPNs.
.SH SYNOPSIS
.nf
.BI atacs " -tL"
.br
.BI atacs> " lhpndbm"
.fi
.SH DESCRIPTION
.B lhpndbm
is a dbm-based analysis engine Labeled Hybrid Petri Nets (LHPNs).
.SH OPTIONS
.TP
.BI \-tL
Enables the lhpndbm method from the command line.
.TP
.BI lhpndbm
Enables the lhpndbm method in the interactive shell.
.SH CREDITS
.B lhpndbm
was primarily written by Scott R. Little.
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR lhpnbdd (1)
.BR http://www.async.ece.utah.edu
