.TH LOADFILE 1 "28 September 2001" "" ""
.SH NAME
loadfile \- Load a file
.SH DESCRIPTION
.B loadfile
selects a design file for synthesis or verification.
.SH "SEE ALSO"
.BR loadcsp (1)
.BR loadhse (1)
.BR loadvhdl (1)
.BR loader (1)
.BR loadtel (1)
.BR loadgraph (1)
.BR loadxbm (1)
.BR loadrsg (1)
.BR loadprs (1)
.BR http://www.async.ece.utah.edu
