.TH PORED 1 "30 September 2001" "" ""
.SH NAME
pored \- Partial Order Reduction
.SH SYNOPSIS
.nf
.BI atacs " -op"
.br
.BI atacs> " pored"
.fi
.SH DESCRIPTION
.B pored
enables partial order reduction to improve efficiency of timing analysis for
synthesis and verification.
.SH OPTIONS
.TP
.BI \-op
Enables the partial order method from the command line.
.TP
.BI pored
Enables the partial order method in the interactive shell.
.SH CREDITS
.B pored
was primarily written by Eric Mercer (eemercer@vlsigroup.elen.utah.edu).
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR abstract (1)
.BR http://www.async.ece.utah.edu
