.TH SHOWNET 1 "28 September 2001" "" ""
.SH NAME
shownet \- Displays a circuit netlists
.SH SYNOPSIS
.nf
.BI atacs " -dn <filename>"
.br
.BI atacs> " shownet <filename>"
.fi
.SH DESCRIPTION
.B shownet
displays the current circuit netlist using Bell Lab's Dot program.
.SH OPTIONS
.TP
.BI \-dn
Displays a circuit netlist from the command line.
.TP
.BI shownet
Displays a circuit netlist from the interactive shell.
.SH CREDITS
.B shownet
was primarily written by and Jeff Cuthbert.
.SH "SEE ALSO"
.BR shower (1)
.BR showstat (1)
.BR showrsg (1)
.BR printer (1)
.BR printrsg (1)
.BR printstat (1)
.BR printreg (1)
.BR printnet (1)
.BR dot (1)
.BR http://www.async.ece.utah.edu
