.TH SHOWER 1 "28 September 2001" "" ""
.SH NAME
shower \- Displays a timed event-rule (or TEL) structure
.SH SYNOPSIS
.nf
.BI atacs " -de <filename>"
.br
.BI atacs> " shower <filename>"
.fi
.SH DESCRIPTION
.B shower
displays the current timed event-rule (or TEL) structure
using Tom Rokicki's parg program or Bell Lab's Dot program depending on
whether the dot options is selected or not.
.SH OPTIONS
.TP
.BI \-de
Displays a timed event-rule (or TEL) structure from the command line.
.TP
.BI shower
Displays a timed event-rule (or TEL) structure from the interactive shell.
.SH CREDITS
.B shower
was primarily written by Chris Myers (myers@vlsigroup.ece.utah.edu)
and Jeff Cuthbert.
.SH "SEE ALSO"
.BR showrsg (1)
.BR showstat (1)
.BR shownet (1)
.BR printer (1)
.BR printrsg (1)
.BR printstat (1)
.BR printreg (1)
.BR printnet (1)
.BR dot (1)
.BR http://www.async.ece.utah.edu
