.TH SHOWLPN 1 "13 December 2006" "" ""
.SH NAME
showlpn \- Displays a currently loaded LHPN
.SH SYNOPSIS
.nf
.BI atacs " -dl <filename>"
.br
.BI atacs> " showlpn <filename>"
.fi
.SH DESCRIPTION
.B showlpn
displays the current LHPN using the selected viewer.
.SH OPTIONS
.TP
.BI \-dl
Displays an LHPN from the command line.
.TP
.BI showlpn
Displays an LHPN from the interactive shell.
.SH CREDITS
.B showlpn
was primarily written by Chris Myers
.SH "SEE ALSO"
.BR loadlpn (1)
.BR storelpn(1)
.BR printlpn (1)
.BR dot (1)
.BR http://www.async.ece.utah.edu
