.TH STOREER 1 "28 September 2001" "" ""
.SH NAME
storeer \- Stores a ER File
.SH SYNOPSIS
.nf
.BI atacs " -se <filename>"
.br
.BI atacs> " storeer <filename>"
.fi
.SH DESCRIPTION
.B storeer
Stores a timed event-rule (ER) structure to a file named <filename>.er.
The file will be in the following form:
.PP
 .e <number of events>
.br
 .i <number of inputs>
.br
 .r <number of causal rules>
.br
 .n <number of ordering rules>
.br
 .d <number of merges>
.br
 .c <number of conflicts>
.br
reset
.br
input events
.br
other events
.br
causal rules in the following form:
.br
<enabling> <enabled> <epsilon> <l> <u> <dist>
.br
ordering rules in the same form:
.br
merges in the following form:
.br
if a disjunctive merge:  <signal+/1> <signal+/2>
.br
if a conjunctive merge:  <signal-/1> <signal-/2>
.br
conflicts in the following form:
.br
<signal+/1> <signal+/2>
.SH OPTIONS
.TP
.BI \-se
Stores a ER file from the command line.
.TP
.BI storeer
Stores a ER file from the interactive shell.
.SH CREDITS
.B storeer
was primarily written by Chris Myers (myers@vlsigroup.ece.utah.edu).
.SH "SEE ALSO"
.BR storeg (1)
.BR storersg (1)
.BR storesg (1)
.BR storeprs (1)
.BR storenet (1)
.BR storevhdl (1)
.BR http://www.async.ece.utah.edu
