.TH STOREVHDL 1 "28 September 2001" "" ""
.SH NAME
storevhdl \- Stores a VHDL File
.SH SYNOPSIS
.nf
.BI atacs " -sv <filename>"
.br
.BI atacs> " storevhdl <filename>"
.fi
.SH DESCRIPTION
.B storevhdl
stores the results of synthesis into a VHDL file named <filename>.vhd.
.SH OPTIONS
.TP
.BI \-sv
Stores a VHDL file from the command line.
.TP
.BI storevhdl
Stores a VHDL file from the interactive shell.
.SH CREDITS
.B storevhdl
was primarily written by Hao Zheng (hao@vlsigroup.ece.utah.edu).
.SH "SEE ALSO"
.BR storeg (1)
.BR storeer (1)
.BR storersg (1)
.BR storesg (1)
.BR storeprs (1)
.BR storenet (1)
.BR http://www.async.ece.utah.edu
