.TH STORENET 1 "28 September 2001" "" ""
.SH NAME
storenet \- Stores a NET File
.SH SYNOPSIS
.nf
.BI atacs " -sn <filename>"
.br
.BI atacs> " storenet <filename>"
.fi
.SH DESCRIPTION
.B storenet
stores the final implementation in netlist format used by the program SYN.
.SH OPTIONS
.TP
.BI \-sn
Stores a NET file from the command line.
.TP
.BI storenet
Stores a NET file from the interactive shell.
.SH CREDITS
.B storenet
was primarily written by Chris Myers (myers@vlsigroup.ece.utah.edu).
.SH "SEE ALSO"
.BR storeg (1)
.BR storeer (1)
.BR storersg (1)
.BR storesg (1)
.BR storeprs (1)
.BR storevhdl (1)
.BR http://www.async.ece.utah.edu
