.TH VERBOSE 1 "30 September 2001" "" ""
.SH NAME
verbose \- Produce All Intermediate Files
.SH SYNOPSIS
.nf
.BI atacs " -ov"
.br
.BI atacs> " verbose"
.fi
.SH DESCRIPTION
.B verbose
mode saves all intermediate results to files. 
Otherwise, only the final result is saved.
.SH OPTIONS
.TP
.BI \-ov
Enables verbose mode from the command line.
.TP
.BI verbose
Enables verbose mode in the interactive shell.
.SH CREDITS
.B verbose
output was written by one and all.
.SH BUGS
.SH FILES
.SH "SEE ALSO"
.BR http://www.async.ece.utah.edu
