#!/bin/bash
echo "ATACS build script generated by: uladzimir.marushka@exposit.com"
sudo apt update
echo "sudo apt install build-essential git"
sudo apt install build-essential git
echo "git clone https://github.com/MyersResearchGroup/ATACS.git"
git clone https://github.com/MyersResearchGroup/ATACS.git
echo "git clone https://github.com/MyersResearchGroup/ATACS.git"
echo "Go To build directory"
read -p "Press enter to continue"
cd ATACS/src
echo "Try build ...."
read -p "Press enter to continue"
make
echo "You see project do not build ...."
read -p "Press enter to continue"
echo "Install extenal libraries ...."
read -p "Press enter to continue"
echo "sudo apt install flex bison sed perl graphviz automake"
sudo apt install flex bison sed perl graphviz automake
sudo cp /usr/bin/aclocal /usr/bin/aclocal-1.14
sudo cp /usr/bin/automake /usr/bin/automake-1.14
mv ../lib/libutil.a ../lib/libCutil.a
echo "mv ../lib/libutil.a ../lib/libCutil.a"
cd ..
echo "git clone https://github.com/ivmai/cudd.git"
git clone https://github.com/ivmai/cudd.git
cd cudd
./configure
make
cp cplusplus/.libs/libobj.a ../lib
cd ../src
echo "Was installed extenal libraries ...."
read -p "Press enter to continue"
echo "Try build ...."
read -p "Press enter to continue"
make static
echo "You see project was build successfully ...."
read -p "Press enter to continue"







