#!/bin/csh

##########################################################################
## egm -- 12/19/00
##
##########################################################################

## Check that a file or files were specified in the command line
if ( $#argv == 0 ) then
  echo "usage: get_data <pattern>"
  exit 1
endif

## For each file provided, try and extract the information
foreach i ($*)
    ## Find "Found" in the file and report the information from
    ## on the line.  Note: the gsub command strips away any 
    ## textual identifiers on the numbers.
    awk 'BEGIN { FS = ":" } \
         $1 == "STATES", $1 == "EDGES" { if ( $1 == "STATES" ||     \
                                              $1 == "EDGES" ) next; \
                                              printf "%s\n", $2; }' $i | sort
    ## Print the \n for the next entry.
end
